### ISSUE TITLE
Documents and Requirements Workflow

### ISSUE THREAD

**Issue by amsmith-pro** [Arrow-air/arrowdrone-docs#2]
## Tasks

- Discuss and agree on a workflow, report decisions on this ticket
    - [ ] Pull Request and Review Process
    - [ ] Approvals
- [ ] Agree on the format of documents
    - All vnv plans, design documents, etc. in markdown, for instance? Open to wild ideas
- [ ] Brainstorm potential CI/CD scripts related to document management
    - Checking out of date references, dates, broken hyperlinks
    - Can create lower priority tickets for these

## Agree on a Workflow

Requirements:
- Version controlled
  - Should also indicate which user modified and when
- Must have parent/child requirement linking
  - See "Traceability" in [DO-178C Wikipedia](https://en.wikipedia.org/wiki/DO-178C)

### Proposal 1

https://github.com/doorstop-dev/doorstop

1. Create `arrowdrone-docs` repository in the Arrow GitHub.
2. Lock the `main` branch.
3. Use [doorstop](https://github.com/doorstop-dev/doorstop) to create individual requirements.
    - Each is its own `.yml` file. See [here](https://github.com/doorstop-dev/doorstop/tree/develop/reqs) for example.
    - You can configure a `.doorstop.yml` file which will determine the required format of the requirements in the directory.
    - You can view requirement all together as HTML - see [here](http://doorstop-dev.github.io/doorstop/HLT.html)
    - doorstop also has a GUI in development
    - Requirements may have been brainstormed in a video call - this is their final location for review
4. A PR is created for modified requirement file(s). 
    - *n* approvals needed for a requirement change to be pushed into the `main` branch.
    - Specific individuals? This will reflect future manned aircraft SW development process

Advantages:
- Pull requests in GitHub have discussion threads. All discussion about why a requirement was changed, who changed it, why, who concurred, etc. occurs here and can be reviewed at any future point, even (especially) after the PR is closed.
- We can extend this workflow to reviewing and approving documentation outside of requirements, for instance V&V plans, software design documents, trade studies, etc."

Proposed repository file tree:
```tree
GitHub
├───arrowdrone-docs (Repository)
│   ├───docs/
│   │   └───vnv-plans/
│   │   └───sdds/
│   └───reqs/ # with doorstop
│   │   └───L1/
│   │   └───L2/
│   │   └───L3/
```

**Comment by owlot** [comment]
Doorstop seems like a good product to use for the DO-178C documentation.
I would personally use Doorstop for just that and keep all other documentation in Docusaurus which is already set up the way you describe for Doorstop.
We have a main and a staging branch. All PR's will go to staging first for review (auto-deploy to staging website), and currently, at least 1 review of a maintainer is needed to merge to main. We can extend this even more with the setup of CODEOWNERS where specific directories need specific reviewers etc.
The Docusaurus docs look a bit more friendly to read in my opinion, but it would require custom changes to comply with the DO-178C documentation. So it's nice that Doorstop covers that part.

**Comment by amsmith-pro** [comment]
I agree, I actually experimented with code owners and approvals for this repository.

As far as engineering documents going on Docusaurus, keep in mind that we'll be having a different set of engineering documents for each project (drone, manned craft, ground station, charging ports, rideshare protocol, etc.). It might make sense to keep these engineering documents in the associated `docs` repo for those projects rather than putting them all in the `website` repo.

Furthermore, changes to requirements in the `docs` repo will often be linked to changes in the engineering documents (for example, changing the rate at which telemetry is to be downlinked), so I would personally prefer to keep them in the same repo. That way we'll see the requirements change and the document changes in the same PR rather than doing two separate reviews.

I won't dig in my heels too much because we can always move things around if one method or the other doesn't work out, just my two cents. Maybe we can find a way to have both, and have pages on the Website generated from files in each of the `docs` repos?
